service: telegramtranslatorbot

provider:
  name: aws
  runtime: python3.6
  environment:
    telegram_token: ${file(./serverless.env.yml):dev.telegram_token}
    yandex_api_key: ${file(./serverless.env.yml):dev.yandex_api_key}

package:
  include:
    - src/**
functions:
  hello:
    handler: src/telegram_app.telegram_trigger
    events:
      - http: POST /

plugins:
  - serverless-python-requirements
